### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "74a744bd55cdb918e56016e093464b7483ac14ea";
          sha256 = "09arxl2xhcy7d1p0f1bc3s7yhxvr955a8mkgdmyssfzij9brkak5";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
    selection = self.selection;
in
{
  format-version = 4;
  ocaml-version = "4.10.0";
  repos = repos;
  selection = 
  {
    angstrom = 
    {
      opamInputs = 
      {
        bigstringaf = selection.bigstringaf;
        dune = selection.dune;
        ocaml = selection.ocaml;
        ocaml-syntax-shims = selection.ocaml-syntax-shims;
        result = selection.result;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0izk8jl0gryfajlvby1yf954mxg9fhw85rcnd36v6l0whsg61x3m";
        package = "packages/angstrom/angstrom.0.15.0";
      };
      pname = "angstrom";
      src = pkgs.fetchurl 
      {
        sha256 = "01cjjal8vjsm225v9y0q6ixam8k5f821rcr6yix6i9nzs84aq6gi";
        url = "https://github.com/inhabitedtype/angstrom/archive/0.15.0.tar.gz";
      };
      version = "0.15.0";
    };
    asetmap = 
    {
      opamInputs = 
      {
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:16nq43lklwzam8bsr1xm61722nvng4b11ixy67jvixmd6a1brygy";
        package = "packages/asetmap/asetmap.0.8.1";
      };
      pname = "asetmap";
      src = pkgs.fetchurl 
      {
        sha256 = "1zjk3xn9167wgsvnwdawhz1das71akxy3ica7vkmag0ycxa1q8a3";
        url = "http://erratique.ch/software/asetmap/releases/asetmap-0.8.1.tbz";
      };
      version = "0.8.1";
    };
    asn1-combinators = 
    {
      opamInputs = 
      {
        bigarray-compat = selection.bigarray-compat;
        cstruct = selection.cstruct;
        dune = selection.dune;
        ocaml = selection.ocaml;
        ptime = selection.ptime;
        stdlib-shims = selection.stdlib-shims;
        zarith = selection.zarith;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1cdx8pdnglq6cikza5h7vjn3a512rfb1ph3j5cj3z4yvqi2n4ivn";
        package = "packages/asn1-combinators/asn1-combinators.0.2.4";
      };
      pname = "asn1-combinators";
      src = pkgs.fetchurl 
      {
        sha256 = "09rn5wwqhwg7x51b9ycl15s7007hgha6lwaz2bpw85fr70jq3i9r";
        url = "https://github.com/mirleft/ocaml-asn1-combinators/releases/download/v0.2.4/asn1-combinators-v0.2.4.tbz";
      };
      version = "0.2.4";
    };
    astring = 
    {
      opamInputs = 
      {
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1djnad9sq12idlakj069xvwm2nn7wqm137pqbxxai5frkgi08x74";
        package = "packages/astring/astring.0.8.5";
      };
      pname = "astring";
      src = pkgs.fetchurl 
      {
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
      };
      version = "0.8.5";
    };
    base = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        dune-configurator = selection.dune-configurator;
        ocaml = selection.ocaml;
        sexplib0 = selection.sexplib0;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1kppnq1za9kqwjaacgs4fl2rwf5k0nq395s916nz618rj5af7q85";
        package = "packages/base/base.v0.14.0";
      };
      pname = "base";
      src = pkgs.fetchurl 
      {
        sha256 = "1rkdhsgbcv0a8p29mwvpd2ldz8cjk97pixl43izm54wyin4lp778";
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/base-v0.14.0.tar.gz";
      };
      version = "v0.14.0";
    };
    base-bytes = 
    {
      opamInputs = 
      {
        ocaml = selection.ocaml;
        ocamlfind = selection.ocamlfind;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
        package = "packages/base-bytes/base-bytes.base";
      };
      pname = "base-bytes";
      src = null;
      version = "base";
    };
    base-threads = 
    {
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
        package = "packages/base-threads/base-threads.base";
      };
      pname = "base-threads";
      src = null;
      version = "base";
    };
    base-unix = 
    {
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
        package = "packages/base-unix/base-unix.base";
      };
      pname = "base-unix";
      src = null;
      version = "base";
    };
    base64 = 
    {
      opamInputs = 
      {
        base-bytes = selection.base-bytes;
        dune = selection.dune;
        dune-configurator = selection.dune-configurator;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0ipgmb0bghmh3svszlpzlsy1b7j084gh818pwqic4dh42w3g3nlb";
        package = "packages/base64/base64.3.4.0";
      };
      pname = "base64";
      src = pkgs.fetchurl 
      {
        sha256 = "0d0n5gd4nkdsz14jnxq13f1f7rzxmndg5xql039a8wfppmazd70w";
        url = "https://github.com/mirage/ocaml-base64/releases/download/v3.4.0/base64-v3.4.0.tbz";
      };
      version = "3.4.0";
    };
    bigarray-compat = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:04frgyb1gmlfjni3dj1zkfsrsw1j6iq13b1k8w7w6ljhxr007wsn";
        package = "packages/bigarray-compat/bigarray-compat.1.0.0";
      };
      pname = "bigarray-compat";
      src = pkgs.fetchurl 
      {
        sha256 = "1bpmmnxb1yx72aqlbdaqfl18rgz1cq9cf6cqvnfl88mz5dfr4x0d";
        url = "https://github.com/mirage/bigarray-compat/archive/v1.0.0.tar.gz";
      };
      version = "1.0.0";
    };
    bigstringaf = 
    {
      opamInputs = 
      {
        bigarray-compat = selection.bigarray-compat;
        conf-pkg-config = selection.conf-pkg-config;
        dune = selection.dune;
        ocaml = selection.ocaml;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:027l5qq6bhws0w5wp85aw5dqs6387ca2zz12njqc42jpcbdv6xbz";
        package = "packages/bigstringaf/bigstringaf.0.7.0";
      };
      pname = "bigstringaf";
      src = pkgs.fetchurl 
      {
        sha256 = "1q4fswcy3n3gja3cnrg3z5wxbl6gh983vsh7ykry6sck961hh2k6";
        url = "https://github.com/inhabitedtype/bigstringaf/archive/0.7.0.tar.gz";
      };
      version = "0.7.0";
    };
    biniou = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        easy-format = selection.easy-format;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:12ykyqa9piw1gny1flsi43qph411alzsm3rr8cgs5ap4drk3xbrd";
        package = "packages/biniou/biniou.1.2.1";
      };
      pname = "biniou";
      src = pkgs.fetchurl 
      {
        sha256 = "0da3m0g0dhl02jfynrbysjh070xk2z6rxcx34xnqx6ljn5l6qm1m";
        url = "https://github.com/mjambon/biniou/releases/download/1.2.1/biniou-1.2.1.tbz";
      };
      version = "1.2.1";
    };
    bos = 
    {
      opamInputs = 
      {
        astring = selection.astring;
        base-unix = selection.base-unix;
        fmt = selection.fmt;
        fpath = selection.fpath;
        logs = selection.logs;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        rresult = selection.rresult;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:076a3ppiizh20fj0mg0xsprshzpdv3j1avfpsxpzaxzh72fchpch";
        package = "packages/bos/bos.0.2.0";
      };
      pname = "bos";
      src = pkgs.fetchurl 
      {
        sha256 = "1s10iqx8rgnxr5n93lf4blwirjf8nlm272yg5sipr7lsr35v49wc";
        url = "http://erratique.ch/software/bos/releases/bos-0.2.0.tbz";
      };
      version = "0.2.0";
    };
    capnp = 
    {
      opamInputs = 
      {
        base = selection.base;
        dune = selection.dune;
        ocaml = selection.ocaml;
        ocplib-endian = selection.ocplib-endian;
        res = selection.res;
        result = selection.result;
        stdint = selection.stdint;
        stdio = selection.stdio;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0spsv50xfh4mip7l54r5l59mz6xpdy80ag9gzlbb5hzhlbipknsr";
        package = "packages/capnp/capnp.3.4.0";
      };
      pname = "capnp";
      src = pkgs.fetchurl 
      {
        sha256 = "0zn1h4qkr613l4p8418qsnw2ndzx37vnk314dwrldlp6pd6hwsvs";
        url = "https://github.com/capnproto/capnp-ocaml/releases/download/v3.4.0/capnp-v3.4.0.tbz";
      };
      version = "3.4.0";
    };
    capnp-rpc = 
    {
      opamInputs = 
      {
        asetmap = selection.asetmap;
        astring = selection.astring;
        dune = selection.dune;
        fmt = selection.fmt;
        logs = selection.logs;
        ocaml = selection.ocaml;
        stdint = selection.stdint;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0rral8xx0x9y5d96jqh90z4r2k4h183g8xg0vv6b6m66mjgmmsp0";
        package = "packages/capnp-rpc/capnp-rpc.0.8.0";
      };
      pname = "capnp-rpc";
      src = pkgs.fetchurl 
      {
        sha256 = "04ask658wx1vcvvcn5jzlg3rz1h3piflcnc71rjynynzy91zgp5x";
        url = "https://github.com/mirage/capnp-rpc/releases/download/v0.8.0/capnp-rpc-v0.8.0.tbz";
      };
      version = "0.8.0";
    };
    capnp-rpc-lwt = 
    {
      opamInputs = 
      {
        asetmap = selection.asetmap;
        astring = selection.astring;
        capnp = selection.capnp;
        capnp-rpc = selection.capnp-rpc;
        conf-capnproto = selection.conf-capnproto;
        dune = selection.dune;
        fmt = selection.fmt;
        logs = selection.logs;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        uri = selection.uri;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0v2a5izbwn5a27avbdb0xla59bxc45h9zi7grm6r83y0llgi2xqc";
        package = "packages/capnp-rpc-lwt/capnp-rpc-lwt.0.8.0";
      };
      pname = "capnp-rpc-lwt";
      src = pkgs.fetchurl 
      {
        sha256 = "04ask658wx1vcvvcn5jzlg3rz1h3piflcnc71rjynynzy91zgp5x";
        url = "https://github.com/mirage/capnp-rpc/releases/download/v0.8.0/capnp-rpc-v0.8.0.tbz";
      };
      version = "0.8.0";
    };
    capnp-rpc-net = 
    {
      opamInputs = 
      {
        asetmap = selection.asetmap;
        asn1-combinators = selection.asn1-combinators;
        astring = selection.astring;
        base64 = selection.base64;
        capnp = selection.capnp;
        capnp-rpc = selection.capnp-rpc;
        capnp-rpc-lwt = selection.capnp-rpc-lwt;
        conf-capnproto = selection.conf-capnproto;
        dune = selection.dune;
        fmt = selection.fmt;
        logs = selection.logs;
        mirage-flow = selection.mirage-flow;
        ocaml = selection.ocaml;
        prometheus = selection.prometheus;
        ptime = selection.ptime;
        tls = selection.tls;
        tls-mirage = selection.tls-mirage;
        uri = selection.uri;
        x509 = selection.x509;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:19bd5q1wifn5maiyvkbg3dh8byj8bsfr54igz44i2h5cw3zcnh9c";
        package = "packages/capnp-rpc-net/capnp-rpc-net.0.8.0";
      };
      pname = "capnp-rpc-net";
      src = pkgs.fetchurl 
      {
        sha256 = "04ask658wx1vcvvcn5jzlg3rz1h3piflcnc71rjynynzy91zgp5x";
        url = "https://github.com/mirage/capnp-rpc/releases/download/v0.8.0/capnp-rpc-v0.8.0.tbz";
      };
      version = "0.8.0";
    };
    capnp-rpc-unix = 
    {
      opamInputs = 
      {
        astring = selection.astring;
        base64 = selection.base64;
        capnp-rpc-net = selection.capnp-rpc-net;
        cmdliner = selection.cmdliner;
        cstruct-lwt = selection.cstruct-lwt;
        dune = selection.dune;
        fmt = selection.fmt;
        logs = selection.logs;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0wrnj2lr02xagi3qx1frqr8c5xkh1fz98b4n8m2vxkr3zbis9fnp";
        package = "packages/capnp-rpc-unix/capnp-rpc-unix.0.8.0";
      };
      pname = "capnp-rpc-unix";
      src = pkgs.fetchurl 
      {
        sha256 = "04ask658wx1vcvvcn5jzlg3rz1h3piflcnc71rjynynzy91zgp5x";
        url = "https://github.com/mirage/capnp-rpc/releases/download/v0.8.0/capnp-rpc-v0.8.0.tbz";
      };
      version = "0.8.0";
    };
    cmdliner = 
    {
      opamInputs = {
                     ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:05qlm4yp6124w2z10dpdchldfrmgmcr6h31rnxp8qs8mk0xzx48z";
        package = "packages/cmdliner/cmdliner.1.0.4";
      };
      pname = "cmdliner";
      src = pkgs.fetchurl 
      {
        sha256 = "1h04q0zkasd0mw64ggh4y58lgzkhg6yhzy60lab8k8zq9ba96ajw";
        url = "http://erratique.ch/software/cmdliner/releases/cmdliner-1.0.4.tbz";
      };
      version = "1.0.4";
    };
    cohttp = 
    {
      opamInputs = 
      {
        base64 = selection.base64;
        dune = selection.dune;
        fieldslib = selection.fieldslib;
        jsonm = selection.jsonm;
        ocaml = selection.ocaml;
        ppx_fields_conv = selection.ppx_fields_conv;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        re = selection.re;
        sexplib0 = selection.sexplib0;
        stdlib-shims = selection.stdlib-shims;
        stringext = selection.stringext;
        uri = selection.uri;
        uri-sexp = selection.uri-sexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1mwhj4yf5v45kxqkys733p6j59img9gv748q956l51fp59bbc3p8";
        package = "packages/cohttp/cohttp.2.5.4";
      };
      pname = "cohttp";
      src = pkgs.fetchurl 
      {
        sha256 = "1q04spmki5zis5p5m1vs77i3k7ijm134j62g61071vblwx25z17a";
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v2.5.4/cohttp-v2.5.4.tbz";
      };
      version = "2.5.4";
    };
    cohttp-lwt = 
    {
      opamInputs = 
      {
        cohttp = selection.cohttp;
        dune = selection.dune;
        logs = selection.logs;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        sexplib0 = selection.sexplib0;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:15dmm1b71mriqc6zpiv3jzp61x8fc8al4s8ps78zihgvpjn5ykca";
        package = "packages/cohttp-lwt/cohttp-lwt.2.5.4";
      };
      pname = "cohttp-lwt";
      src = pkgs.fetchurl 
      {
        sha256 = "1q04spmki5zis5p5m1vs77i3k7ijm134j62g61071vblwx25z17a";
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v2.5.4/cohttp-v2.5.4.tbz";
      };
      version = "2.5.4";
    };
    cohttp-lwt-unix = 
    {
      opamInputs = 
      {
        base-unix = selection.base-unix;
        cmdliner = selection.cmdliner;
        cohttp-lwt = selection.cohttp-lwt;
        conduit-lwt-unix = selection.conduit-lwt-unix;
        dune = selection.dune;
        fmt = selection.fmt;
        logs = selection.logs;
        lwt = selection.lwt;
        magic-mime = selection.magic-mime;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:01yfqcjgkgwfhakchvnqb87gq6wqqs0v2530l60q1mvdip5x1iv4";
        package = "packages/cohttp-lwt-unix/cohttp-lwt-unix.2.5.4";
      };
      pname = "cohttp-lwt-unix";
      src = pkgs.fetchurl 
      {
        sha256 = "1q04spmki5zis5p5m1vs77i3k7ijm134j62g61071vblwx25z17a";
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v2.5.4/cohttp-v2.5.4.tbz";
      };
      version = "2.5.4";
    };
    conduit = 
    {
      opamInputs = 
      {
        astring = selection.astring;
        dune = selection.dune;
        ipaddr = selection.ipaddr;
        ipaddr-sexp = selection.ipaddr-sexp;
        logs = selection.logs;
        ocaml = selection.ocaml;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        sexplib = selection.sexplib;
        uri = selection.uri;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1pffrv5zf76xf2n7chjb9gzwd736k7p53a4msv53d8i25qnx1wl3";
        package = "packages/conduit/conduit.2.1.0";
      };
      pname = "conduit";
      src = pkgs.fetchurl 
      {
        sha256 = "0wkyyzc194x1cvb7khxjzkf0jch5m7y6bmxmq5vxrm3yrbxd2kbv";
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v2.1.0/conduit-v2.1.0.tbz";
      };
      version = "2.1.0";
    };
    conduit-lwt = 
    {
      opamInputs = 
      {
        base-unix = selection.base-unix;
        conduit = selection.conduit;
        dune = selection.dune;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        sexplib = selection.sexplib;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:07qvchqwysk2vn28440qjqyjsmw93czcxq77gwnz21qywfzn5lh7";
        package = "packages/conduit-lwt/conduit-lwt.2.1.0";
      };
      pname = "conduit-lwt";
      src = pkgs.fetchurl 
      {
        sha256 = "0wkyyzc194x1cvb7khxjzkf0jch5m7y6bmxmq5vxrm3yrbxd2kbv";
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v2.1.0/conduit-v2.1.0.tbz";
      };
      version = "2.1.0";
    };
    conduit-lwt-unix = 
    {
      opamInputs = 
      {
        base-unix = selection.base-unix;
        conduit-lwt = selection.conduit-lwt;
        dune = selection.dune;
        ipaddr = selection.ipaddr;
        ipaddr-sexp = selection.ipaddr-sexp;
        launchd = selection.launchd or null;
        lwt = selection.lwt;
        lwt_ssl = selection.lwt_ssl or null;
        ocaml = selection.ocaml;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        tls = selection.tls or null;
        uri = selection.uri;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1b18p85np301pwgqaxskh86nyx737qd0lfjdwg4hyw54v4hs68h3";
        package = "packages/conduit-lwt-unix/conduit-lwt-unix.2.2.2";
      };
      pname = "conduit-lwt-unix";
      src = pkgs.fetchurl 
      {
        sha256 = "1zb83w2pq9c8xrappfxa6y5q93772f5dj22x78camsm77a2c2z55";
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v2.2.2/conduit-v2.2.2.tbz";
      };
      version = "2.2.2";
    };
    conf-capnproto = 
    {
      buildInputs = [ (pkgs.capnp or null) (pkgs.capnproto or null)
                       (pkgs."capnproto-dev@testing" or null)
                       (pkgs.epel-release or null)
                       (pkgs.libcapnp-dev or null) ];
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:15g6xwbnq9rjjzpn8i3pv87jaazkagnhq2nq6q3vhc5ky7nbdkd3";
        package = "packages/conf-capnproto/conf-capnproto.1";
      };
      pname = "conf-capnproto";
      src = null;
      version = "1";
    };
    conf-gmp = 
    {
      buildInputs = [ (pkgs.gmp or null) (pkgs.gmp-dev or null)
                       (pkgs.gmp-devel or null) (pkgs.libgmp-dev or null) ];
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1favh1cypqclm5d2mnllmwzg9ir7jjrclcnhpx88h2amhidq0mbq";
        package = "packages/conf-gmp/conf-gmp.2";
      };
      pname = "conf-gmp";
      src = null;
      version = "2";
    };
    conf-gmp-powm-sec = 
    {
      opamInputs = {
                     conf-gmp = selection.conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:01i1z8spjwhw7a8fj4jbd19lykxva28yc70rckd34pbp8v0lkhbi";
        package = "packages/conf-gmp-powm-sec/conf-gmp-powm-sec.2";
      };
      pname = "conf-gmp-powm-sec";
      src = null;
      version = "2";
    };
    conf-m4 = 
    {
      buildInputs = [ (pkgs.m4) ];
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1jlhg718lz35jyr5w0sgvg5ycplhnd8653rc4980yci8p3z1vlxs";
        package = "packages/conf-m4/conf-m4.1";
      };
      pname = "conf-m4";
      src = null;
      version = "1";
    };
    conf-perl = 
    {
      buildInputs = [ (pkgs.perl) ];
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1w4gn91js0fmai0gp87x190cdpn86r8bw676xq7bs7zvx14c2may";
        package = "packages/conf-perl/conf-perl.1";
      };
      pname = "conf-perl";
      src = null;
      version = "1";
    };
    conf-pkg-config = 
    {
      buildInputs = [ (pkgs.pkgconfig) ];
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:14b3gf8fslh6i2s4h0w689p3qswa19ach4ag7gnrjb3qc0qmgmsj";
        package = "packages/conf-pkg-config/conf-pkg-config.1.3";
      };
      pname = "conf-pkg-config";
      src = null;
      version = "1.3";
    };
    conf-sqlite3 = 
    {
      buildInputs = [ (pkgs.sqlite) ];
      opamInputs = 
      {
        conf-pkg-config = selection.conf-pkg-config;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:00lkznklcb0v5jb0q156dma604mg9rsmhdl59bc09p50ic35qsh8";
        package = "packages/conf-sqlite3/conf-sqlite3.1";
      };
      pname = "conf-sqlite3";
      src = null;
      version = "1";
    };
    cppo = 
    {
      opamInputs = 
      {
        base-unix = selection.base-unix;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0hdl429cpb4bg9gc07rxs14p7d3r3nfi3vw6s38c6xhf412nl611";
        package = "packages/cppo/cppo.1.6.6";
      };
      pname = "cppo";
      src = pkgs.fetchurl 
      {
        sha256 = "185q0x54id7pfc6rkbjscav8sjkrg78fz65rgfw7b4bqlyb2j9z7";
        url = "https://github.com/ocaml-community/cppo/releases/download/v1.6.6/cppo-v1.6.6.tbz";
      };
      version = "1.6.6";
    };
    cpuid = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1k2l7zn9dgyyg7h2x45xbq04hsq4700hmibzyif8l2pkil6lqkdy";
        package = "packages/cpuid/cpuid.0.1.2";
      };
      pname = "cpuid";
      src = pkgs.fetchurl 
      {
        sha256 = "08ng4mva6qblb5ipkrxbr0my7ndkc4qwcbswkqgbgir864s74m93";
        url = "https://github.com/pqwy/cpuid/releases/download/v0.1.2/cpuid-v0.1.2.tbz";
      };
      version = "0.1.2";
    };
    csexp = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
        result = selection.result;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1vhvnfmgpl5dymh0mpqfmyk9vhkhscvjp6ym2hqm7sl7fvflgfn2";
        package = "packages/csexp/csexp.1.3.2";
      };
      pname = "csexp";
      src = pkgs.fetchurl 
      {
        sha256 = "0jhwrxfjb0x31xj4g4b89fzw34sq19j0rq2hs2zyh1vz4xxl47zj";
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.3.2/csexp-1.3.2.tbz";
      };
      version = "1.3.2";
    };
    cstruct = 
    {
      opamInputs = 
      {
        bigarray-compat = selection.bigarray-compat;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0y9yd5sf5bpmnf36259il1asr1gmy2wkrfzd7wc0yzrnzy6fji79";
        package = "packages/cstruct/cstruct.6.0.0";
      };
      pname = "cstruct";
      src = pkgs.fetchurl 
      {
        sha256 = "0xi6cj85z033fqrqdkwac6gg07629vzdhx03c3lhiwwc4lpnv8bq";
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.0/cstruct-v6.0.0.tbz";
      };
      version = "6.0.0";
    };
    cstruct-lwt = 
    {
      opamInputs = 
      {
        base-unix = selection.base-unix;
        cstruct = selection.cstruct;
        dune = selection.dune;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0n8akwiv8bgp5651pk9ayy1ak9q3mvk9li65r4rr1gz3cghiifd5";
        package = "packages/cstruct-lwt/cstruct-lwt.6.0.0";
      };
      pname = "cstruct-lwt";
      src = pkgs.fetchurl 
      {
        sha256 = "0xi6cj85z033fqrqdkwac6gg07629vzdhx03c3lhiwwc4lpnv8bq";
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.0/cstruct-v6.0.0.tbz";
      };
      version = "6.0.0";
    };
    cstruct-sexp = 
    {
      opamInputs = 
      {
        cstruct = selection.cstruct;
        dune = selection.dune;
        ocaml = selection.ocaml;
        sexplib = selection.sexplib;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1n28s5c018adiibdy0jscs1ldzlwsq239mm78wvjpf7gfaczwpm6";
        package = "packages/cstruct-sexp/cstruct-sexp.6.0.0";
      };
      pname = "cstruct-sexp";
      src = pkgs.fetchurl 
      {
        sha256 = "0xi6cj85z033fqrqdkwac6gg07629vzdhx03c3lhiwwc4lpnv8bq";
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.0/cstruct-v6.0.0.tbz";
      };
      version = "6.0.0";
    };
    current = 
    {
      opamInputs = 
      {
        bos = selection.bos;
        cmdliner = selection.cmdliner;
        current_incr = selection.current_incr;
        dune = selection.dune;
        duration = selection.duration;
        fmt = selection.fmt;
        lwt = selection.lwt;
        lwt-dllist = selection.lwt-dllist;
        ocaml = selection.ocaml;
        ppx_deriving = selection.ppx_deriving;
        prometheus = selection.prometheus;
        re = selection.re;
        sqlite3 = selection.sqlite3;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:11dlyvqb27rky1yjyavxsnbdj7khwc83dm0xmy40h2myncq1z6wv";
        package = "packages/current/current.0.3";
      };
      pname = "current";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    current_ansi = 
    {
      opamInputs = 
      {
        astring = selection.astring;
        dune = selection.dune;
        fmt = selection.fmt;
        ocaml = selection.ocaml;
        tyxml = selection.tyxml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0yda0cwl94q9gklqfnvzjbykw5f3zm43yd4mwz5ykp653my2fg9l";
        package = "packages/current_ansi/current_ansi.0.3";
      };
      pname = "current_ansi";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    current_docker = 
    {
      opamInputs = 
      {
        current = selection.current;
        current_git = selection.current_git;
        dockerfile = selection.dockerfile;
        dune = selection.dune;
        fmt = selection.fmt;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        ppx_deriving = selection.ppx_deriving;
        ppx_deriving_yojson = selection.ppx_deriving_yojson;
        yojson = selection.yojson;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:00129bgiqn61iiisyik6yvvqgb3n69b1hf483ql5pd6fik2k1arb";
        package = "packages/current_docker/current_docker.0.3";
      };
      pname = "current_docker";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    current_examples = 
    {
      opamInputs = 
      {
        capnp-rpc-unix = selection.capnp-rpc-unix;
        cmdliner = selection.cmdliner;
        current = selection.current;
        current_docker = selection.current_docker;
        current_git = selection.current_git;
        current_github = selection.current_github;
        current_rpc = selection.current_rpc;
        current_web = selection.current_web;
        dune = selection.dune;
        duration = selection.duration;
        fmt = selection.fmt;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0lmmk4bxlyb9m5dkhgig1y9gafckhmvxllhpzcm9sli79q0ywr0y";
        package = "packages/current_examples/current_examples.0.3";
      };
      pname = "current_examples";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    current_git = 
    {
      opamInputs = 
      {
        current = selection.current;
        dune = selection.dune;
        fmt = selection.fmt;
        irmin-watcher = selection.irmin-watcher;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        ppx_deriving = selection.ppx_deriving;
        ppx_deriving_yojson = selection.ppx_deriving_yojson;
        yojson = selection.yojson;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0brk9vvhs9fv4dic1qgds1j689f7c57v0915akmvv9qxrkbycn99";
        package = "packages/current_git/current_git.0.3";
      };
      pname = "current_git";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    current_github = 
    {
      opamInputs = 
      {
        cohttp-lwt-unix = selection.cohttp-lwt-unix;
        current = selection.current;
        current_git = selection.current_git;
        current_web = selection.current_web;
        dune = selection.dune;
        fmt = selection.fmt;
        lwt = selection.lwt;
        mirage-crypto = selection.mirage-crypto;
        mirage-crypto-pk = selection.mirage-crypto-pk;
        ocaml = selection.ocaml;
        tls = selection.tls;
        x509 = selection.x509;
        yojson = selection.yojson;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1kn8jzff41nh4sv4sm8isxyjqvvqzzsbz9bkcbl8kmgh5wzkb6vr";
        package = "packages/current_github/current_github.0.3";
      };
      pname = "current_github";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    current_incr = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:061zkwznd3lha5n9z09akbz4vj0k091l2mlxq97n4lyxpyyw1697";
        package = "packages/current_incr/current_incr.0.3";
      };
      pname = "current_incr";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    current_rpc = 
    {
      opamInputs = 
      {
        capnp-rpc-lwt = selection.capnp-rpc-lwt;
        dune = selection.dune;
        fpath = selection.fpath;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1wl68n3c9g1770gfvy2s96zdsxdq3m7ndas7ijaarc59zmfwli29";
        package = "packages/current_rpc/current_rpc.0.3";
      };
      pname = "current_rpc";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    current_web = 
    {
      opamInputs = 
      {
        base64 = selection.base64;
        bos = selection.bos;
        cmdliner = selection.cmdliner;
        cohttp-lwt-unix = selection.cohttp-lwt-unix;
        current = selection.current;
        current_ansi = selection.current_ansi;
        dune = selection.dune;
        fmt = selection.fmt;
        lwt = selection.lwt;
        mirage-crypto-rng = selection.mirage-crypto-rng;
        ocaml = selection.ocaml;
        ppx_deriving_yojson = selection.ppx_deriving_yojson;
        prometheus-app = selection.prometheus-app;
        routes = selection.routes;
        session = selection.session;
        session-cohttp-lwt = selection.session-cohttp-lwt;
        tyxml = selection.tyxml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0iyl388ad27va591gd53pdxm31gq18i3v8gpnxaz38qkgd6qampy";
        package = "packages/current_web/current_web.0.3";
      };
      pname = "current_web";
      src = pkgs.fetchurl 
      {
        sha256 = "1v1qn9f5fgfygxz1wmxl0zr3ffknxm78hkn7fy2j1hbny6msjf62";
        url = "https://github.com/ocurrent/ocurrent/releases/download/v0.3/current-v0.3.tbz";
      };
      version = "0.3";
    };
    dockerfile = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        fmt = selection.fmt;
        ocaml = selection.ocaml;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        sexplib = selection.sexplib;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0larfwmq1jp0nv7ci77lq25iqkjjbk9md9r0n5qri66k0gjx2n46";
        package = "packages/dockerfile/dockerfile.7.0.0";
      };
      pname = "dockerfile";
      src = pkgs.fetchurl 
      {
        sha256 = "1p6bf7px3a7n75qy89d7gd8g38hrd7b0667kkyx25rkis771arvx";
        url = "https://github.com/avsm/ocaml-dockerfile/releases/download/v7.0.0/dockerfile-v7.0.0.tbz";
      };
      version = "7.0.0";
    };
    domain-name = 
    {
      opamInputs = 
      {
        astring = selection.astring;
        dune = selection.dune;
        fmt = selection.fmt;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1243f92lmszqdf9qvh1v6wv3jd9r5k2h1fhbqqfw9j3imjdfhw0a";
        package = "packages/domain-name/domain-name.0.3.0";
      };
      pname = "domain-name";
      src = pkgs.fetchurl 
      {
        sha256 = "12kc9p2a2fi1ipc2hyhbzivxpph3npglxwdgvhd6v20rqqdyvnad";
        url = "https://github.com/hannesm/domain-name/releases/download/v0.3.0/domain-name-v0.3.0.tbz";
      };
      version = "0.3.0";
    };
    dune = 
    {
      opamInputs = 
      {
        base-threads = selection.base-threads;
        base-unix = selection.base-unix;
        ocaml = selection.ocaml or null;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0xl07c5sr54aq45a3xszns1rg5ml5ap4m2gc0g0jf82y4yh1ly95";
        package = "packages/dune/dune.2.7.1";
      };
      pname = "dune";
      src = pkgs.fetchurl 
      {
        sha256 = "0pcjf209gynjwipnpplaqyvyivnawqiwhvqnivhkybisicpqyln3";
        url = "https://github.com/ocaml/dune/releases/download/2.7.1/dune-2.7.1.tbz";
      };
      version = "2.7.1";
    };
    dune-configurator = 
    {
      opamInputs = 
      {
        csexp = selection.csexp;
        dune = selection.dune;
        ocaml = selection.ocaml;
        result = selection.result;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0mv26dnvvbij3gcsnyk88xmy950dqi7lh919fqnrqd10c5y0v4dx";
        package = "packages/dune-configurator/dune-configurator.2.7.1";
      };
      pname = "dune-configurator";
      src = pkgs.fetchurl 
      {
        sha256 = "0pcjf209gynjwipnpplaqyvyivnawqiwhvqnivhkybisicpqyln3";
        url = "https://github.com/ocaml/dune/releases/download/2.7.1/dune-2.7.1.tbz";
      };
      version = "2.7.1";
    };
    duration = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1ki5q3czl28bj1xdc0fw7h7qw7fxk9n3az2za12521z56yxlgfiq";
        package = "packages/duration/duration.0.1.3";
      };
      pname = "duration";
      src = pkgs.fetchurl 
      {
        sha256 = "0m9r0ayhpl98g9vdxrbjdcllns274jilic5v8xj1x7dphw21p95h";
        url = "https://github.com/hannesm/duration/releases/download/0.1.3/duration-0.1.3.tbz";
      };
      version = "0.1.3";
    };
    easy-format = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1zahpwp0021xygbwpygrrwa5g65qq6dfqngckb3823ybc6l79lva";
        package = "packages/easy-format/easy-format.1.3.2";
      };
      pname = "easy-format";
      src = pkgs.fetchurl 
      {
        sha256 = "09hrikx310pac2sb6jzaa7k6fmiznnmhdsqij1gawdymhawc4h1l";
        url = "https://github.com/mjambon/easy-format/releases/download/1.3.2/easy-format-1.3.2.tbz";
      };
      version = "1.3.2";
    };
    eqaf = 
    {
      opamInputs = 
      {
        bigarray-compat = selection.bigarray-compat or null;
        cstruct = selection.cstruct or null;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1479110ad2z0s58w6vwfhp8m01yj5yki5zhx5lppjfrh1p9whm0l";
        package = "packages/eqaf/eqaf.0.7";
      };
      pname = "eqaf";
      src = pkgs.fetchurl 
      {
        sha256 = "1q09pwhs121vpficl2af1yzs4y7dd9bc1lcxbqyfc4x4m6p6drhh";
        url = "https://github.com/mirage/eqaf/releases/download/v0.7/eqaf-v0.7.tbz";
      };
      version = "0.7";
    };
    fiat-p256 = 
    {
      opamInputs = 
      {
        bigarray-compat = selection.bigarray-compat;
        conf-pkg-config = selection.conf-pkg-config;
        cstruct = selection.cstruct;
        dune = selection.dune;
        dune-configurator = selection.dune-configurator;
        eqaf = selection.eqaf;
        hex = selection.hex;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0qpq4qi5cd5ah0k3yn3bb77hvvl0vi1x9wpn2jg9dijwbclh2pxk";
        package = "packages/fiat-p256/fiat-p256.0.2.3";
      };
      pname = "fiat-p256";
      src = pkgs.fetchurl 
      {
        sha256 = "1q5hfhs9bhl9ph84jj7pv8al51pvxns5ap57lqf136zmjl9in3f2";
        url = "https://github.com/mirage/fiat/releases/download/v0.2.3/fiat-p256-v0.2.3.tbz";
      };
      version = "0.2.3";
    };
    fieldslib = 
    {
      opamInputs = 
      {
        base = selection.base;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1ayrqisqs2shn9nlga3pz3k84y12bw5b6cr6fi8rgv5gi9hr33lq";
        package = "packages/fieldslib/fieldslib.v0.14.0";
      };
      pname = "fieldslib";
      src = pkgs.fetchurl 
      {
        sha256 = "10n5y376fb5jgqk9h8vq158rm1b36h9lzh6p11q33h6xgvb1v6n3";
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/fieldslib-v0.14.0.tar.gz";
      };
      version = "v0.14.0";
    };
    fmt = 
    {
      opamInputs = 
      {
        base-unix = selection.base-unix or null;
        cmdliner = selection.cmdliner or null;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        seq = selection.seq;
        stdlib-shims = selection.stdlib-shims;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1lvq50p7a5i59jqkn4zijxm9p92c6phi20akdj3qbmlnjn8lqs7h";
        package = "packages/fmt/fmt.0.8.9";
      };
      pname = "fmt";
      src = pkgs.fetchurl 
      {
        sha256 = "0gkkkj4x678vxdda4xaw2dd44qjacavsvn5nx8gydfwah6pjbkxk";
        url = "https://erratique.ch/software/fmt/releases/fmt-0.8.9.tbz";
      };
      version = "0.8.9";
    };
    fpath = 
    {
      opamInputs = 
      {
        astring = selection.astring;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1pnskgw9fqq4kg1x4sc4vcv9rh0kksilx4qngwafpyss42mqq2i2";
        package = "packages/fpath/fpath.0.7.3";
      };
      pname = "fpath";
      src = pkgs.fetchurl 
      {
        sha256 = "03z7mj0sqdz465rc4drj1gr88l9q3nfs374yssvdjdyhjbqqzc0j";
        url = "https://erratique.ch/software/fpath/releases/fpath-0.7.3.tbz";
      };
      version = "0.7.3";
    };
    gmap = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0pliwm7xynn6a810zg2ywp1nxwqjs9y7akx5lslhk4h63j41i5ac";
        package = "packages/gmap/gmap.0.3.0";
      };
      pname = "gmap";
      src = pkgs.fetchurl 
      {
        sha256 = "073wa0lrb0jj706j87cwzf1a8d1ff14100mnrjs8z3xc4ri9xp84";
        url = "https://github.com/hannesm/gmap/releases/download/0.3.0/gmap-0.3.0.tbz";
      };
      version = "0.3.0";
    };
    hacl_x25519 = 
    {
      opamInputs = 
      {
        conf-pkg-config = selection.conf-pkg-config;
        cstruct = selection.cstruct;
        dune = selection.dune;
        eqaf = selection.eqaf;
        ocaml = selection.ocaml;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0wdr3p6h4ya587sih7kfiqk2br6ab9ilvf83rsqr8fxw9nmyl9ns";
        package = "packages/hacl_x25519/hacl_x25519.0.2.2";
      };
      pname = "hacl_x25519";
      src = pkgs.fetchurl 
      {
        sha256 = "0baprhr46vm6a585qi1jjbajhsh21gjxdklqdl79swzrx2l58rw1";
        url = "https://github.com/mirage/hacl/releases/download/v0.2.2/hacl_x25519-v0.2.2.tbz";
      };
      version = "0.2.2";
    };
    hex = 
    {
      opamInputs = 
      {
        bigarray-compat = selection.bigarray-compat;
        cstruct = selection.cstruct;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1p6fbjw8ymp4i5w1v6lcslvc7dq1pkz364kbi22jn6zvm9fpg9k6";
        package = "packages/hex/hex.1.4.0";
      };
      pname = "hex";
      src = pkgs.fetchurl 
      {
        sha256 = "07b9y0lmnflsslkrm6xilkj40n8sf2hjqkyqghnk7sw5l0plkqsp";
        url = "https://github.com/mirage/ocaml-hex/releases/download/v1.4.0/hex-v1.4.0.tbz";
      };
      version = "1.4.0";
    };
    hkdf = 
    {
      opamInputs = 
      {
        cstruct = selection.cstruct;
        dune = selection.dune;
        mirage-crypto = selection.mirage-crypto;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0bdiwwqjc58xn851vyi6ghsbw0h6bkvsy5hbc5wqgmfrz29x4q8a";
        package = "packages/hkdf/hkdf.1.0.4";
      };
      pname = "hkdf";
      src = pkgs.fetchurl 
      {
        sha256 = "0nzx6vzbc1hh6vx1ly8df4b16lgps6zjpp9mjycsnnn49bddc9mr";
        url = "https://github.com/hannesm/ocaml-hkdf/releases/download/v1.0.4/hkdf-v1.0.4.tbz";
      };
      version = "1.0.4";
    };
    ipaddr = 
    {
      opamInputs = 
      {
        domain-name = selection.domain-name;
        dune = selection.dune;
        macaddr = selection.macaddr;
        ocaml = selection.ocaml;
        stdlib-shims = selection.stdlib-shims;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:19npiyy1ps0lgz3n7abqphvhx1y6pg91j2ygnas5qjgjcydssxwn";
        package = "packages/ipaddr/ipaddr.5.0.1";
      };
      pname = "ipaddr";
      src = pkgs.fetchurl 
      {
        sha256 = "00k6sw0hz145p83b8c4hgib90cqhsgk35pbhrqx8v4zzik1w7xq0";
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.0.1/ipaddr-v5.0.1.tbz";
      };
      version = "5.0.1";
    };
    ipaddr-sexp = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ipaddr = selection.ipaddr;
        ocaml = selection.ocaml;
        ppx_sexp_conv = selection.ppx_sexp_conv;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1piymj138wj8apb7mnhbmr2qbv7y2aqb41f7n9im1z0517y7bh37";
        package = "packages/ipaddr-sexp/ipaddr-sexp.5.0.1";
      };
      pname = "ipaddr-sexp";
      src = pkgs.fetchurl 
      {
        sha256 = "00k6sw0hz145p83b8c4hgib90cqhsgk35pbhrqx8v4zzik1w7xq0";
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.0.1/ipaddr-v5.0.1.tbz";
      };
      version = "5.0.1";
    };
    irmin-watcher = 
    {
      opamInputs = 
      {
        astring = selection.astring;
        fmt = selection.fmt;
        inotify = selection.inotify or null;
        jbuilder = selection.jbuilder;
        logs = selection.logs;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        osx-fsevents = selection.osx-fsevents or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:16kch0q07zggvd7gk5d9s8vlybdssg2rpdl5m6hpmadjwqvw8rbq";
        package = "packages/irmin-watcher/irmin-watcher.0.3.0";
      };
      pname = "irmin-watcher";
      src = pkgs.fetchurl 
      {
        sha256 = "1731nqmnwgh27mis55l441yawcqyyvq0lqnf3pjcjvghbyq5rmm8";
        url = "https://github.com/mirage/irmin-watcher/releases/download/0.3.0/irmin-watcher-0.3.0.tbz";
      };
      version = "0.3.0";
    };
    jbuilder = 
    {
      opamInputs = {
                     ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1phf81qmqcc88nxnl3i92jnv4j07vw5a71lmag9vpky3n1h4qkjv";
        package = "packages/jbuilder/jbuilder.1.0+beta20.2";
      };
      pname = "jbuilder";
      src = pkgs.fetchurl 
      {
        sha256 = "1516rq0x0481bfg9436k1c74346y8nw45shizsnkwylfdj9p8p65";
        url = "https://github.com/ocaml/dune/releases/download/1.0%2Bbeta20.2/jbuilder-1.0+beta20.2.tbz";
      };
      version = "1.0-beta20.2";
    };
    jsonm = 
    {
      opamInputs = 
      {
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        topkg = selection.topkg;
        uchar = selection.uchar;
        uutf = selection.uutf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0dj8ibg6j4r4a7v7g6d6q3h4m23jv3pxwc7nam4zzbc7h2k69dy9";
        package = "packages/jsonm/jsonm.1.0.1";
      };
      pname = "jsonm";
      src = pkgs.fetchurl 
      {
        sha256 = "1176dcmxb11fnw49b7yysvkjh0kpzx4s48lmdn5psq9vshp5c29w";
        url = "http://erratique.ch/software/jsonm/releases/jsonm-1.0.1.tbz";
      };
      version = "1.0.1";
    };
    logs = 
    {
      opamInputs = 
      {
        base-threads = selection.base-threads or null;
        cmdliner = selection.cmdliner or null;
        fmt = selection.fmt or null;
        js_of_ocaml = selection.js_of_ocaml or null;
        lwt = selection.lwt or null;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1k797gb7f2s1hlqyqsq2xyq9gm20l5q2iwh26bs44f3bp3gklg1a";
        package = "packages/logs/logs.0.7.0";
      };
      pname = "logs";
      src = pkgs.fetchurl 
      {
        sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
        url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
      };
      version = "0.7.0";
    };
    lwt = 
    {
      opamInputs = 
      {
        base-threads = selection.base-threads or null;
        base-unix = selection.base-unix or null;
        conf-libev = selection.conf-libev or null;
        cppo = selection.cppo;
        dune = selection.dune;
        dune-configurator = selection.dune-configurator;
        mmap = selection.mmap;
        ocaml = selection.ocaml;
        ocaml-syntax-shims = selection.ocaml-syntax-shims or null;
        ocplib-endian = selection.ocplib-endian;
        result = selection.result;
        seq = selection.seq;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0vkirigcvw92z0x0r4nhkmb9mmrsqjn6kaxc2fnjic0cz321866i";
        package = "packages/lwt/lwt.5.3.0";
      };
      pname = "lwt";
      src = pkgs.fetchurl 
      {
        sha256 = "1barwvlyqd3xiqhqr01yrcygjvn26yz0rdh68rgnhyx0g21r5kiq";
        url = "https://github.com/ocsigen/lwt/archive/5.3.0.tar.gz";
      };
      version = "5.3.0";
    };
    lwt-dllist = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1d1jdj7wpxm055zvvbn4gi0pps5b026qgmv5p3srch310p6qm7kw";
        package = "packages/lwt-dllist/lwt-dllist.1.0.0";
      };
      pname = "lwt-dllist";
      src = pkgs.fetchurl 
      {
        sha256 = "0g111f8fq9k1hwccpkhylkp83f73mlz4xnxxr3rf9xpi2f8fh7j9";
        url = "https://github.com/mirage/lwt-dllist/releases/download/v1.0.0/lwt-dllist-v1.0.0.tbz";
      };
      version = "1.0.0";
    };
    macaddr = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0m0q3s62m2l6vy9nyb6673wi8j1zmk6pd1ngq7458lsahdz1l9vk";
        package = "packages/macaddr/macaddr.5.0.1";
      };
      pname = "macaddr";
      src = pkgs.fetchurl 
      {
        sha256 = "00k6sw0hz145p83b8c4hgib90cqhsgk35pbhrqx8v4zzik1w7xq0";
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.0.1/ipaddr-v5.0.1.tbz";
      };
      version = "5.0.1";
    };
    magic-mime = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0d8ici4l55iywi80a5rp2mhzni1ppp16vb9f4zsml1898cd92p7l";
        package = "packages/magic-mime/magic-mime.1.1.2";
      };
      pname = "magic-mime";
      src = pkgs.fetchurl 
      {
        sha256 = "1sq4rfd9m3693cnzlbds4qh1xpvrv1iz1s1f75nvacbmfjy0nn8c";
        url = "https://github.com/mirage/ocaml-magic-mime/releases/download/v1.1.2/magic-mime-v1.1.2.tbz";
      };
      version = "1.1.2";
    };
    mirage-clock = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0b5phjj2ng5j4a6090gxj871ssdzl5b412lilpxqgaqy00rs1cfn";
        package = "packages/mirage-clock/mirage-clock.3.1.0";
      };
      pname = "mirage-clock";
      src = pkgs.fetchurl 
      {
        sha256 = "0cqa07aqkamw0dvis1fl46brvk81zvb92iy5076ik62gv9n5a0mn";
        url = "https://github.com/mirage/mirage-clock/releases/download/v3.1.0/mirage-clock-v3.1.0.tbz";
      };
      version = "3.1.0";
    };
    mirage-crypto = 
    {
      opamInputs = 
      {
        conf-pkg-config = selection.conf-pkg-config;
        cstruct = selection.cstruct;
        dune = selection.dune;
        dune-configurator = selection.dune-configurator;
        eqaf = selection.eqaf;
        ocaml = selection.ocaml;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0xf6x15rgixn8p9lrsplk7hk5fijc25cpn9k7hx22n7q7gjf2asa";
        package = "packages/mirage-crypto/mirage-crypto.0.8.7";
      };
      pname = "mirage-crypto";
      src = pkgs.fetchurl 
      {
        sha256 = "1gx86h6kk39zq3kvl854jc2ap2755paalp1f7iv8r9js2xnbxfxy";
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.8.7/mirage-crypto-v0.8.7.tbz";
      };
      version = "0.8.7";
    };
    mirage-crypto-pk = 
    {
      opamInputs = 
      {
        conf-gmp-powm-sec = selection.conf-gmp-powm-sec;
        cstruct = selection.cstruct;
        dune = selection.dune;
        eqaf = selection.eqaf;
        mirage-crypto = selection.mirage-crypto;
        mirage-crypto-rng = selection.mirage-crypto-rng;
        mirage-no-solo5 = selection.mirage-no-solo5 or null;
        mirage-no-xen = selection.mirage-no-xen or null;
        ocaml = selection.ocaml;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        rresult = selection.rresult;
        sexplib = selection.sexplib;
        zarith = selection.zarith;
        zarith-freestanding = selection.zarith-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:137fzkhlbskgb4gdzaqvygfn4yxa1qxy4l28bbvavhgap4gc7500";
        package = "packages/mirage-crypto-pk/mirage-crypto-pk.0.8.7";
      };
      pname = "mirage-crypto-pk";
      src = pkgs.fetchurl 
      {
        sha256 = "1gx86h6kk39zq3kvl854jc2ap2755paalp1f7iv8r9js2xnbxfxy";
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.8.7/mirage-crypto-v0.8.7.tbz";
      };
      version = "0.8.7";
    };
    mirage-crypto-rng = 
    {
      opamInputs = 
      {
        cstruct = selection.cstruct;
        dune = selection.dune;
        dune-configurator = selection.dune-configurator;
        duration = selection.duration;
        logs = selection.logs;
        lwt = selection.lwt;
        mirage-crypto = selection.mirage-crypto;
        mtime = selection.mtime;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0bh113qh67cmgawzdf5lxw0fpva9f1s5acdmip48frw13g56ghld";
        package = "packages/mirage-crypto-rng/mirage-crypto-rng.0.8.7";
      };
      pname = "mirage-crypto-rng";
      src = pkgs.fetchurl 
      {
        sha256 = "1gx86h6kk39zq3kvl854jc2ap2755paalp1f7iv8r9js2xnbxfxy";
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.8.7/mirage-crypto-v0.8.7.tbz";
      };
      version = "0.8.7";
    };
    mirage-device = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        fmt = selection.fmt;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0r6k677xdxlhmfw7lpn5cj7xi639yqxzyzckfzn0x3w0f1kx32w8";
        package = "packages/mirage-device/mirage-device.2.0.0";
      };
      pname = "mirage-device";
      src = pkgs.fetchurl 
      {
        sha256 = "18alxyi6wlxqvb4lajjlbdfkgcajsmklxi9xqmpcz07j51knqa04";
        url = "https://github.com/mirage/mirage-device/releases/download/v2.0.0/mirage-device-v2.0.0.tbz";
      };
      version = "2.0.0";
    };
    mirage-flow = 
    {
      opamInputs = 
      {
        cstruct = selection.cstruct;
        dune = selection.dune;
        fmt = selection.fmt;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1r8dkdh1i5129g4mszqq4b95lb9w4hlqfqqqc4zvzmzk0cq5fii2";
        package = "packages/mirage-flow/mirage-flow.2.0.1";
      };
      pname = "mirage-flow";
      src = pkgs.fetchurl 
      {
        sha256 = "13v05x34six0z6bc2is8qhvbxk4knxh80ardi5x4rl738vlq3mn9";
        url = "https://github.com/mirage/mirage-flow/releases/download/v2.0.1/mirage-flow-v2.0.1.tbz";
      };
      version = "2.0.1";
    };
    mirage-kv = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        fmt = selection.fmt;
        lwt = selection.lwt;
        mirage-device = selection.mirage-device;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0dsji2a8dmdimlf6qpxgg6xiyv2a21h2mfsm0zrfdkd11nisnna4";
        package = "packages/mirage-kv/mirage-kv.3.0.1";
      };
      pname = "mirage-kv";
      src = pkgs.fetchurl 
      {
        sha256 = "1n736sjvdd8rkbc2b5jm9sn0w6hvhjycma5328r0l03v24vk5cki";
        url = "https://github.com/mirage/mirage-kv/releases/download/v3.0.1/mirage-kv-v3.0.1.tbz";
      };
      version = "3.0.1";
    };
    mirage-no-solo5 = 
    {
      opamInputs = {
                     ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:18h50v7lp39sis6jy46h35vij0v1z5fr76c4y2h4b72c40fwwck1";
        package = "packages/mirage-no-solo5/mirage-no-solo5.1";
      };
      pname = "mirage-no-solo5";
      src = null;
      version = "1";
    };
    mirage-no-xen = 
    {
      opamInputs = {
                     ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1nvmvay3nkl8ljw9f46dwv3jppqbbkp0pxf9f1gq4spckb8ysmkh";
        package = "packages/mirage-no-xen/mirage-no-xen.1";
      };
      pname = "mirage-no-xen";
      src = null;
      version = "1";
    };
    mmap = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0mjn2jxrfwlrzppjnc6pg47ncm0ri6a1hn3kj2yz10rmpca25bsm";
        package = "packages/mmap/mmap.1.1.0";
      };
      pname = "mmap";
      src = pkgs.fetchurl 
      {
        sha256 = "0l6waidal2n8mkdn74avbslvc10sf49f5d889n838z03pra5chsc";
        url = "https://github.com/mirage/mmap/releases/download/v1.1.0/mmap-v1.1.0.tbz";
      };
      version = "1.1.0";
    };
    mtime = 
    {
      opamInputs = 
      {
        js_of_ocaml = selection.js_of_ocaml or null;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1pvlkp6n3z75mjc5y0nvhf2s7fmzj8k84chwzvmyrpb786s9gqyh";
        package = "packages/mtime/mtime.1.2.0";
      };
      pname = "mtime";
      src = pkgs.fetchurl 
      {
        sha256 = "0zm1jvqkz3ghznfsm3bbv9q2zinp9grggdf7k9phjazjvny68xb8";
        url = "https://erratique.ch/software/mtime/releases/mtime-1.2.0.tbz";
      };
      version = "1.2.0";
    };
    nocrypto = 
    {
      opamInputs = 
      {
        cpuid = selection.cpuid;
        cstruct = selection.cstruct;
        cstruct-lwt = selection.cstruct-lwt;
        lwt = selection.lwt;
        mirage-entropy = selection.mirage-entropy or null;
        mirage-no-solo5 = selection.mirage-no-solo5 or null;
        mirage-no-xen = selection.mirage-no-xen or null;
        mirage-solo5 = selection.mirage-solo5 or null;
        mirage-xen = selection.mirage-xen or null;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        ocb-stubblr = selection.ocb-stubblr;
        ppx_deriving = selection.ppx_deriving;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        sexplib = selection.sexplib;
        topkg = selection.topkg;
        zarith = selection.zarith;
        zarith-freestanding = selection.zarith-freestanding or null;
        zarith-xen = selection.zarith-xen or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1jv8vy88drd4pdg29ggs0zq9kx417knjnp3zrycnh5srq7f68qdc";
        package = "packages/nocrypto/nocrypto.0.5.4-2";
      };
      pname = "nocrypto";
      src = pkgs.fetchurl 
      {
        sha256 = "0zshi9hlhcz61n5z1k6fx6rsi0pl4xgahsyl2jp0crqkaf3hqwlg";
        url = "https://github.com/mirleft/ocaml-nocrypto/releases/download/v0.5.4/nocrypto-0.5.4.tbz";
      };
      version = "0.5.4-2";
    };
    num = 
    {
      opamInputs = 
      {
        ocaml = selection.ocaml;
        ocamlfind = selection.ocamlfind;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:01k7lkq8ika76vaj6rfvq6v5q8ch9jd8iw5zx82anl6jkl274wkn";
        package = "packages/num/num.1.4";
      };
      pname = "num";
      src = pkgs.fetchurl 
      {
        sha256 = "090gl27g84r3s2b12vgkz8fp269jqlrhx4lpg7008yviisv8hl01";
        url = "https://github.com/ocaml/num/archive/v1.4.tar.gz";
      };
      version = "1.4";
    };
    ocaml = 
    {
      opamInputs = 
      {
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
        ocaml-config = selection.ocaml-config;
        ocaml-system = selection.ocaml-system or null;
        ocaml-variants = selection.ocaml-variants or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1j9xgxnbgzrar4rwynm7jd0bi3f5qwwkgyxvk1pd8iazvn81pgya";
        package = "packages/ocaml/ocaml.4.10.0";
      };
      pname = "ocaml";
      src = null;
      version = "4.10.0";
    };
    ocaml-base-compiler = 
    {
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0wavwn6cq999v787fsxf0v2z71h1vwhxwqbidznc4f9ccwjcdc76";
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.10.0";
      };
      pname = "ocaml-base-compiler";
      src = pkgs.fetchurl 
      {
        sha256 = "0fdw4abyp37q7acqaqawy64gakpg7xckw5ssfpn8dbwxlzqf1fjq";
        url = "https://github.com/ocaml/ocaml/archive/4.10.0.tar.gz";
      };
      version = "4.10.0";
    };
    ocaml-compiler-libs = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0z6sqlawly39g8bxax8c97ir8gq4rl9rqjlx69gg672c561knavh";
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.3";
      };
      pname = "ocaml-compiler-libs";
      src = pkgs.fetchurl 
      {
        sha256 = "1jg32fjr7n4933r01iqgablshagx20vgjkjh5pdbn54w8cqkah58";
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.3/ocaml-compiler-libs-v0.12.3.tbz";
      };
      version = "v0.12.3";
    };
    ocaml-config = 
    {
      opamInputs = 
      {
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-variants = selection.ocaml-variants or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0g5s0yysgqdrbgx7vyh56fhx59xypw6hdwlcbzbqcgvj4zp4yy0c";
        package = "packages/ocaml-config/ocaml-config.1";
      };
      pname = "ocaml-config";
      src = null;
      version = "1";
    };
    ocaml-migrate-parsetree = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:18cw30az9wgpqjvg7fcdjgxzi294nkxriilan81nxw7bszmhs08l";
        package = "packages/ocaml-migrate-parsetree/ocaml-migrate-parsetree.2.1.0";
      };
      pname = "ocaml-migrate-parsetree";
      src = pkgs.fetchurl 
      {
        sha256 = "07x7lm45kny0mi0fjvzw51445brm0dgy099cw0gpyly0wj77hyrq";
        url = "https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases/download/v2.1.0/ocaml-migrate-parsetree-v2.1.0.tbz";
      };
      version = "2.1.0";
    };
    ocaml-syntax-shims = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0zhmv9pr3rryn8a08g8vka0viscryd7fkn5gj2294pw6fygv5m4h";
        package = "packages/ocaml-syntax-shims/ocaml-syntax-shims.1.0.0";
      };
      pname = "ocaml-syntax-shims";
      src = pkgs.fetchurl 
      {
        sha256 = "1j7848khli4p7j8i2kmnvhdnhcwhy3zgdpf5ds5ic30ax69y3cl9";
        url = "https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz";
      };
      version = "1.0.0";
    };
    ocamlbuild = 
    {
      opamInputs = {
                     ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0hrzb4fgz7qh7cr65j5yq6fai82fhyl6bp8s9pwcj1a2yhczbviv";
        package = "packages/ocamlbuild/ocamlbuild.0.14.0";
      };
      pname = "ocamlbuild";
      src = pkgs.fetchurl 
      {
        sha256 = "0y1fskw9rg2y1zgb7whv3v8v4xw04svgxslf3856q2aqd7lrrcl7";
        url = "https://github.com/ocaml/ocamlbuild/archive/0.14.0.tar.gz";
      };
      version = "0.14.0";
    };
    ocamlfind = 
    {
      opamInputs = 
      {
        conf-m4 = selection.conf-m4;
        graphics = selection.graphics or null;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:04z3rq1y20wfzmwvjm9wlg89cqqs8n37inhbwp4x2dsqbn0hqd81";
        package = "packages/ocamlfind/ocamlfind.1.8.1";
      };
      pname = "ocamlfind";
      src = pkgs.fetchurl 
      {
        sha256 = "00s3sfb02pnjmkax25pcnljcnhcggiliccfz69a72ic7gsjwz1cf";
        url = "http://download.camlcity.org/download/findlib-1.8.1.tar.gz";
      };
      version = "1.8.1";
    };
    ocb-stubblr = 
    {
      opamInputs = 
      {
        astring = selection.astring;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1lsn82a3pfnl0hwng4nxd9kyrn6dlj05anlxf1vkvi12qj4yfbhq";
        package = "packages/ocb-stubblr/ocb-stubblr.0.1.1-1";
      };
      pname = "ocb-stubblr";
      src = pkgs.fetchurl 
      {
        sha256 = "167b7x1j21mkviq8dbaa0nmk4rps2ilvzwx02igsc2706784z72f";
        url = "https://github.com/pqwy/ocb-stubblr/releases/download/v0.1.1/ocb-stubblr-0.1.1.tbz";
      };
      version = "0.1.1-1";
    };
    ocplib-endian = 
    {
      opamInputs = 
      {
        base-bytes = selection.base-bytes;
        cppo = selection.cppo;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0j5ymxa4ky208k8m4bprvmvbqf9jnr4d0xwdaivznbv85jq9hw4q";
        package = "packages/ocplib-endian/ocplib-endian.1.1";
      };
      pname = "ocplib-endian";
      src = pkgs.fetchurl 
      {
        sha256 = "0qy5q7p11gxi5anhvi8jj6mr80ml0ih8lax5k579rsr2hsp3sns5";
        url = "https://github.com/OCamlPro/ocplib-endian/archive/1.1.tar.gz";
      };
      version = "1.1";
    };
    parsexp = 
    {
      opamInputs = 
      {
        base = selection.base;
        dune = selection.dune;
        ocaml = selection.ocaml;
        sexplib0 = selection.sexplib0;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:187z69l5222908gdp098b4zll925jdn2kml3wyw1lm9jzwwqhmq2";
        package = "packages/parsexp/parsexp.v0.14.0";
      };
      pname = "parsexp";
      src = pkgs.fetchurl 
      {
        sha256 = "158znj19dvfdcwsgzs3rdhxpj1g4aw0d4nkfr8c05bahf0lnshlb";
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/parsexp-v0.14.0.tar.gz";
      };
      version = "v0.14.0";
    };
    ppx_cstruct = 
    {
      opamInputs = 
      {
        cstruct = selection.cstruct;
        dune = selection.dune;
        ocaml = selection.ocaml;
        ppxlib = selection.ppxlib;
        sexplib = selection.sexplib;
        stdlib-shims = selection.stdlib-shims;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:069z03c9pjy65vn48mvab74zbhh0jlqbry15n949xwlad3j3352v";
        package = "packages/ppx_cstruct/ppx_cstruct.6.0.0";
      };
      pname = "ppx_cstruct";
      src = pkgs.fetchurl 
      {
        sha256 = "0xi6cj85z033fqrqdkwac6gg07629vzdhx03c3lhiwwc4lpnv8bq";
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.0/cstruct-v6.0.0.tbz";
      };
      version = "6.0.0";
    };
    ppx_derivers = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0r8rjp4m5jfbf3wz8qlgh82pxjws4arjwxhqq0zjglby6l6h8p3x";
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
      };
      pname = "ppx_derivers";
      src = pkgs.fetchurl 
      {
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
      };
      version = "1.2.1";
    };
    ppx_deriving = 
    {
      opamInputs = 
      {
        cppo = selection.cppo;
        dune = selection.dune;
        ocaml = selection.ocaml;
        ocamlfind = selection.ocamlfind;
        ppx_derivers = selection.ppx_derivers;
        ppxlib = selection.ppxlib;
        result = selection.result;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0a6h3vggxsx2pmhfn3c16viz74q1qnay91y78rn290wphd4w8gmn";
        package = "packages/ppx_deriving/ppx_deriving.5.2";
      };
      pname = "ppx_deriving";
      src = pkgs.fetchurl 
      {
        sha256 = "1rifvap3pr80qlmhy5swk71lb01wlb1qnv5zcp1m18sch8k2cb8w";
        url = "https://github.com/ocaml-ppx/ppx_deriving/releases/download/v5.2/ppx_deriving-v5.2.tbz";
      };
      version = "5.2";
    };
    ppx_deriving_yojson = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
        ppx_deriving = selection.ppx_deriving;
        ppxlib = selection.ppxlib;
        result = selection.result;
        yojson = selection.yojson;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:08vl3y1m0jc32j7m4zkp08c4czv369vahgj2cfny36bg7j3bvyyy";
        package = "packages/ppx_deriving_yojson/ppx_deriving_yojson.3.6.1";
      };
      pname = "ppx_deriving_yojson";
      src = pkgs.fetchurl 
      {
        sha256 = "1rj4i6l47f7pqr7cfxsfh05i5srb5pp9ns6df9719pbhghhfjbki";
        url = "https://github.com/ocaml-ppx/ppx_deriving_yojson/releases/download/v3.6.1/ppx_deriving_yojson-v3.6.1.tbz";
      };
      version = "3.6.1";
    };
    ppx_fields_conv = 
    {
      opamInputs = 
      {
        base = selection.base;
        dune = selection.dune;
        fieldslib = selection.fieldslib;
        ocaml = selection.ocaml;
        ppxlib = selection.ppxlib;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1nycsravcyajfrw9bckc2pk1rc6lmqyx9cvqpmw7nlvfb1wbnq0q";
        package = "packages/ppx_fields_conv/ppx_fields_conv.v0.14.2";
      };
      pname = "ppx_fields_conv";
      src = pkgs.fetchurl 
      {
        sha256 = "0r7d51j54r1za6bwqsmhmhhfab8n10zyk5zznhkm91f20dx9ddip";
        url = "https://github.com/janestreet/ppx_fields_conv/archive/v0.14.2.tar.gz";
      };
      version = "v0.14.2";
    };
    ppx_sexp_conv = 
    {
      opamInputs = 
      {
        base = selection.base;
        dune = selection.dune;
        ocaml = selection.ocaml;
        ppxlib = selection.ppxlib;
        sexplib0 = selection.sexplib0;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0hr0h59jc6kgd5ml6appb589xkvzc1i8yzmp6ijrc33qrz13pvbq";
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.14.2";
      };
      pname = "ppx_sexp_conv";
      src = pkgs.fetchurl 
      {
        sha256 = "156v1bn45621424nsiymf0478ajpx29i97yv2sv23kdy6aij44x9";
        url = "https://github.com/janestreet/ppx_sexp_conv/archive/v0.14.2.tar.gz";
      };
      version = "v0.14.2";
    };
    ppxlib = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
        ocaml-compiler-libs = selection.ocaml-compiler-libs;
        ocaml-migrate-parsetree = selection.ocaml-migrate-parsetree;
        ppx_derivers = selection.ppx_derivers;
        sexplib0 = selection.sexplib0;
        stdlib-shims = selection.stdlib-shims;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:10ir6ky8c86qahywq0gm29j5xhsy9cb1195sa0mqj22xljdi6s30";
        package = "packages/ppxlib/ppxlib.0.20.0";
      };
      pname = "ppxlib";
      src = pkgs.fetchurl 
      {
        sha256 = "0dxd5inxv12rx9kikl21y384m7cpylyvbjslw69rrpjpy8z91d8w";
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.20.0/ppxlib-0.20.0.tbz";
      };
      version = "0.20.0";
    };
    prometheus = 
    {
      opamInputs = 
      {
        asetmap = selection.asetmap;
        astring = selection.astring;
        dune = selection.dune;
        fmt = selection.fmt;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        re = selection.re;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:196i3hhwyc1d8lywsbjm29f1njq05g6f3ryq37himcdl6nml57is";
        package = "packages/prometheus/prometheus.0.7";
      };
      pname = "prometheus";
      src = pkgs.fetchurl 
      {
        sha256 = "1ibakk31cnnfyxiiavpp2h93l4ll83c8359mn6as1ydr9bhlv2g2";
        url = "https://github.com/mirage/prometheus/releases/download/v0.7/prometheus-v0.7.tbz";
      };
      version = "0.7";
    };
    prometheus-app = 
    {
      opamInputs = 
      {
        cmdliner = selection.cmdliner;
        cohttp = selection.cohttp;
        cohttp-lwt = selection.cohttp-lwt;
        cohttp-lwt-unix = selection.cohttp-lwt-unix;
        dune = selection.dune;
        fmt = selection.fmt;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        prometheus = selection.prometheus;
        re = selection.re;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:08vfn602d4i378cr756fsihf279kwhw1vndghlk4l6mclrj8w9kl";
        package = "packages/prometheus-app/prometheus-app.0.7";
      };
      pname = "prometheus-app";
      src = pkgs.fetchurl 
      {
        sha256 = "1ibakk31cnnfyxiiavpp2h93l4ll83c8359mn6as1ydr9bhlv2g2";
        url = "https://github.com/mirage/prometheus/releases/download/v0.7/prometheus-v0.7.tbz";
      };
      version = "0.7";
    };
    ptime = 
    {
      opamInputs = 
      {
        js_of_ocaml = selection.js_of_ocaml or null;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        result = selection.result;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0ldzn2jmz8c3n9rr4mqyfa92lkb3378cmik3klznbln7lsf4fa1v";
        package = "packages/ptime/ptime.0.8.5";
      };
      pname = "ptime";
      src = pkgs.fetchurl 
      {
        sha256 = "1fxq57xy1ajzfdnvv5zfm7ap2nf49znw5f9gbi4kb9vds942ij27";
        url = "https://erratique.ch/software/ptime/releases/ptime-0.8.5.tbz";
      };
      version = "0.8.5";
    };
    re = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
        seq = selection.seq;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:10m5h5myw3pnjvk7z1j7hhx18zpbm7kad2196ljgvj7y169zba61";
        package = "packages/re/re.1.9.0";
      };
      pname = "re";
      src = pkgs.fetchurl 
      {
        sha256 = "1gas4ky49zgxph3870nffzkr6y41kkpqp4nj38pz1gh49zcf12aj";
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.9.0/re-1.9.0.tbz";
      };
      version = "1.9.0";
    };
    res = 
    {
      opamInputs = 
      {
        base-bytes = selection.base-bytes;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0ihpwpq8lz7zx52xqx8485fjcx5p3c56bhmxabzw7n3vfk3z6kpy";
        package = "packages/res/res.5.0.1";
      };
      pname = "res";
      src = pkgs.fetchurl 
      {
        sha256 = "03kix34jm4s67v51dj8bxjs8xxvyywrnmvk2my0bb7az00qw6amd";
        url = "https://github.com/mmottl/res/releases/download/5.0.1/res-5.0.1.tbz";
      };
      version = "5.0.1";
    };
    result = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1c7lw8dbchllz3rl801xwpm82r427vnrv7b7kqh0gwjglya50y28";
        package = "packages/result/result.1.5";
      };
      pname = "result";
      src = pkgs.fetchurl 
      {
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
      };
      version = "1.5";
    };
    routes = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1ws133vpwnnscl595ylra5izd3p91apxazmdfvsi2l8hb41rlb82";
        package = "packages/routes/routes.0.8.0";
      };
      pname = "routes";
      src = pkgs.fetchurl 
      {
        sha256 = "0ikw5b4jrif0psk5kiwagyg15fwypff2b8xzhq9qr80zsq2nny7s";
        url = "https://github.com/anuragsoni/routes/releases/download/0.8.0/routes-0.8.0.tbz";
      };
      version = "0.8.0";
    };
    rresult = 
    {
      opamInputs = 
      {
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        result = selection.result;
        topkg = selection.topkg;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:10vaq82rzip2rn1rbq27pjckvqassjh1n58pnsypldqaahxnbca6";
        package = "packages/rresult/rresult.0.6.0";
      };
      pname = "rresult";
      src = pkgs.fetchurl 
      {
        sha256 = "1k69a3gvrk7f2cshwjzvk7818f0bwxhacgd14wxy6d4gmrggci86";
        url = "http://erratique.ch/software/rresult/releases/rresult-0.6.0.tbz";
      };
      version = "0.6.0";
    };
    seq = 
    {
      opamInputs = {
                     ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
        package = "packages/seq/seq.base";
      };
      pname = "seq";
      src = null;
      version = "base";
    };
    session = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        nocrypto = selection.nocrypto;
        ocaml = selection.ocaml;
        result = selection.result;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1abiwmprhs0q8l6hfb6d4xhwxgx6qf2r3z447ndp90629zvmhkdd";
        package = "packages/session/session.0.4.1";
      };
      pname = "session";
      src = pkgs.fetchurl 
      {
        sha256 = "1r9kphs1g08ca7lkcg4as2192vs5s4181584cpa7bs8cxdf7jmhr";
        url = "https://github.com/inhabitedtype/ocaml-session/archive/0.4.1.tar.gz";
      };
      version = "0.4.1";
    };
    session-cohttp = 
    {
      opamInputs = 
      {
        cohttp = selection.cohttp;
        dune = selection.dune;
        ocaml = selection.ocaml;
        session = selection.session;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1b1yp2bq95kdyrd4ma06wk2gbj509azyf0gxqfra5hqdfj9spqpw";
        package = "packages/session-cohttp/session-cohttp.0.4.1";
      };
      pname = "session-cohttp";
      src = pkgs.fetchurl 
      {
        sha256 = "1r9kphs1g08ca7lkcg4as2192vs5s4181584cpa7bs8cxdf7jmhr";
        url = "https://github.com/inhabitedtype/ocaml-session/archive/0.4.1.tar.gz";
      };
      version = "0.4.1";
    };
    session-cohttp-lwt = 
    {
      opamInputs = 
      {
        cohttp-lwt = selection.cohttp-lwt;
        dune = selection.dune;
        lwt = selection.lwt;
        ocaml = selection.ocaml;
        session-cohttp = selection.session-cohttp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:11lw8vc377qjx1mpvb09qj2ipvw155j6c4nwf9vifflch4jj9rrh";
        package = "packages/session-cohttp-lwt/session-cohttp-lwt.0.4.1";
      };
      pname = "session-cohttp-lwt";
      src = pkgs.fetchurl 
      {
        sha256 = "1r9kphs1g08ca7lkcg4as2192vs5s4181584cpa7bs8cxdf7jmhr";
        url = "https://github.com/inhabitedtype/ocaml-session/archive/0.4.1.tar.gz";
      };
      version = "0.4.1";
    };
    sexplib = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        num = selection.num;
        ocaml = selection.ocaml;
        parsexp = selection.parsexp;
        sexplib0 = selection.sexplib0;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:13jidm5wz2q2a8d52mkc3gl596vlqmpblbsjbq484kjpd0w6yz0f";
        package = "packages/sexplib/sexplib.v0.14.0";
      };
      pname = "sexplib";
      src = pkgs.fetchurl 
      {
        sha256 = "12rlnc6fcrjfdn3gs2agi418sj54ighhs6dfll37zcv7mgywblm2";
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib-v0.14.0.tar.gz";
      };
      version = "v0.14.0";
    };
    sexplib0 = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0xgkp4gm3yc47xdqzmz064qn40fp27k4ar5axi5i1wffg15qavd4";
        package = "packages/sexplib0/sexplib0.v0.14.0";
      };
      pname = "sexplib0";
      src = pkgs.fetchurl 
      {
        sha256 = "0adrc0r1vvvr41dcpj8jwkzh1dfgqf0mks9xlnnskqfm3a51iavg";
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib0-v0.14.0.tar.gz";
      };
      version = "v0.14.0";
    };
    sqlite3 = 
    {
      opamInputs = 
      {
        conf-sqlite3 = selection.conf-sqlite3;
        dune = selection.dune;
        dune-configurator = selection.dune-configurator;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:08wsy44d54vkg8jqdhxmh9pn6z04whs8z7zsc2cyf8h0rv8dnad1";
        package = "packages/sqlite3/sqlite3.5.0.2";
      };
      pname = "sqlite3";
      src = pkgs.fetchurl 
      {
        sha256 = "0sba74n0jvzxibrclhbpqscil36yfw7i9jj9q562yhza6rax9p82";
        url = "https://github.com/mmottl/sqlite3-ocaml/releases/download/5.0.2/sqlite3-5.0.2.tbz";
      };
      version = "5.0.2";
    };
    stdint = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0qlshfpkbpgl6anqrsf58r40y4shasp1hc4zam2dpajlvbfmry6i";
        package = "packages/stdint/stdint.0.7.0";
      };
      pname = "stdint";
      src = pkgs.fetchurl 
      {
        sha256 = "1p2j282d0rzgm8029yx5bc29w8xa23cskg1vmzkrcawfynp6dk2g";
        url = "https://github.com/andrenth/ocaml-stdint/releases/download/0.7.0/stdint-0.7.0.tbz";
      };
      version = "0.7.0";
    };
    stdio = 
    {
      opamInputs = 
      {
        base = selection.base;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0czx19l4sb9v80vwig8fwsn5h8xp44j9v5db2b251zkj71dzd9qx";
        package = "packages/stdio/stdio.v0.14.0";
      };
      pname = "stdio";
      src = pkgs.fetchurl 
      {
        sha256 = "1hj5hraprqy2i90a690l11yjszvb99j818q3d684ryx6p2lddk0l";
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/stdio-v0.14.0.tar.gz";
      };
      version = "v0.14.0";
    };
    stdlib-shims = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0mpni0zab3jy8w1dynklcywgcqhxd7nis66jzhslc09vq8linnhq";
        package = "packages/stdlib-shims/stdlib-shims.0.1.0";
      };
      pname = "stdlib-shims";
      src = pkgs.fetchurl 
      {
        sha256 = "1jv6yb47f66239m7hsz7zzw3i48mjpbvfgpszws48apqx63wjwsk";
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.1.0/stdlib-shims-0.1.0.tbz";
      };
      version = "0.1.0";
    };
    stringext = 
    {
      opamInputs = 
      {
        base-bytes = selection.base-bytes;
        dune = selection.dune;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:15m8a67mps6y22mm5sxpw9b0lldfcmsxim7b331d4qv3l86118gs";
        package = "packages/stringext/stringext.1.6.0";
      };
      pname = "stringext";
      src = pkgs.fetchurl 
      {
        sha256 = "1sh6nafi3i9773j5mlwwz3kxfzdjzsfqj2qibxhigawy5vazahfv";
        url = "https://github.com/rgrinberg/stringext/releases/download/1.6.0/stringext-1.6.0.tbz";
      };
      version = "1.6.0";
    };
    tls = 
    {
      opamInputs = 
      {
        cstruct = selection.cstruct;
        cstruct-sexp = selection.cstruct-sexp;
        domain-name = selection.domain-name;
        dune = selection.dune;
        fiat-p256 = selection.fiat-p256;
        fmt = selection.fmt;
        hacl_x25519 = selection.hacl_x25519;
        hkdf = selection.hkdf;
        logs = selection.logs;
        lwt = selection.lwt;
        mirage-crypto = selection.mirage-crypto;
        mirage-crypto-pk = selection.mirage-crypto-pk;
        mirage-crypto-rng = selection.mirage-crypto-rng;
        ocaml = selection.ocaml;
        ppx_cstruct = selection.ppx_cstruct;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        ptime = selection.ptime;
        sexplib = selection.sexplib;
        x509 = selection.x509;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:17jkyp8apw60yjn800k290fg16541ldmvkf2vbblblgs19x14lhw";
        package = "packages/tls/tls.0.12.6";
      };
      pname = "tls";
      src = pkgs.fetchurl 
      {
        sha256 = "14b2289nhb65qm8wrw51y8qgz5ysn8hcbrj5plznd1pdzl46zxc9";
        url = "https://github.com/mirleft/ocaml-tls/releases/download/v0.12.6/tls-v0.12.6.tbz";
      };
      version = "0.12.6";
    };
    tls-mirage = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        fiat-p256 = selection.fiat-p256;
        fmt = selection.fmt;
        hacl_x25519 = selection.hacl_x25519;
        lwt = selection.lwt;
        mirage-clock = selection.mirage-clock;
        mirage-crypto = selection.mirage-crypto;
        mirage-crypto-pk = selection.mirage-crypto-pk;
        mirage-flow = selection.mirage-flow;
        mirage-kv = selection.mirage-kv;
        ocaml = selection.ocaml;
        ptime = selection.ptime;
        tls = selection.tls;
        x509 = selection.x509;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1a16vjrbri7pkpf7g90by9wdmrp0cvd07wfqrgrrkir22kzlsaxc";
        package = "packages/tls-mirage/tls-mirage.0.12.6";
      };
      pname = "tls-mirage";
      src = pkgs.fetchurl 
      {
        sha256 = "14b2289nhb65qm8wrw51y8qgz5ysn8hcbrj5plznd1pdzl46zxc9";
        url = "https://github.com/mirleft/ocaml-tls/releases/download/v0.12.6/tls-v0.12.6.tbz";
      };
      version = "0.12.6";
    };
    topkg = 
    {
      opamInputs = 
      {
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1asjip3cr84b1n1n4q8b5zrcki87niz6imb9m9zaj2kqdywmp0m5";
        package = "packages/topkg/topkg.1.0.3";
      };
      pname = "topkg";
      src = pkgs.fetchurl 
      {
        sha256 = "0b77gsz9bqby8v77kfi4lans47x9p2lmzanzwins5r29maphb8y6";
        url = "http://erratique.ch/software/topkg/releases/topkg-1.0.3.tbz";
      };
      version = "1.0.3";
    };
    tyxml = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ocaml = selection.ocaml;
        re = selection.re;
        seq = selection.seq;
        uutf = selection.uutf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1q246zb57qzc8v8a2yznc069jh1rxazd8hbgjs0pgk1dgfy7m4bs";
        package = "packages/tyxml/tyxml.4.4.0";
      };
      pname = "tyxml";
      src = pkgs.fetchurl 
      {
        sha256 = "0c150h2f4c4id73ickkdqkir3jya66m6c7f5jxlp4caw9bfr8qsi";
        url = "https://github.com/ocsigen/tyxml/releases/download/4.4.0/tyxml-4.4.0.tbz";
      };
      version = "4.4.0";
    };
    uchar = 
    {
      opamInputs = 
      {
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:17sfpyj5a1z3knnjvnfa5vql6cj2x9pzgzk8w4jrvd2zii2bwpcl";
        package = "packages/uchar/uchar.0.0.2";
      };
      pname = "uchar";
      src = pkgs.fetchurl 
      {
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
      };
      version = "0.0.2";
    };
    uri = 
    {
      opamInputs = 
      {
        angstrom = selection.angstrom;
        dune = selection.dune;
        ocaml = selection.ocaml;
        stringext = selection.stringext;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:04fybs6isdmzcg7nbpx9vbvd0i4ln2557bjk5r736ia8nvap3pvv";
        package = "packages/uri/uri.4.0.0";
      };
      pname = "uri";
      src = pkgs.fetchurl 
      {
        sha256 = "13r9nkgym9z3dqxkyf0yyaqlrk5r3pjdw0kfzvrc90bmhwl9j380";
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.0.0/uri-v4.0.0.tbz";
      };
      version = "4.0.0";
    };
    uri-sexp = 
    {
      opamInputs = 
      {
        dune = selection.dune;
        ppx_sexp_conv = selection.ppx_sexp_conv;
        sexplib0 = selection.sexplib0;
        uri = selection.uri;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1g22g2g9axd0q6f2n3kmdmklifiya9r88xrfxymk0mfpw81y5a3a";
        package = "packages/uri-sexp/uri-sexp.4.0.0";
      };
      pname = "uri-sexp";
      src = pkgs.fetchurl 
      {
        sha256 = "13r9nkgym9z3dqxkyf0yyaqlrk5r3pjdw0kfzvrc90bmhwl9j380";
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.0.0/uri-v4.0.0.tbz";
      };
      version = "4.0.0";
    };
    uutf = 
    {
      opamInputs = 
      {
        cmdliner = selection.cmdliner or null;
        ocaml = selection.ocaml;
        ocamlbuild = selection.ocamlbuild;
        ocamlfind = selection.ocamlfind;
        topkg = selection.topkg;
        uchar = selection.uchar;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1j4hkk196lg1dsnf6jb1n8y3na606lkfb5vlr0gjb53qc7pdh6cy";
        package = "packages/uutf/uutf.1.0.2";
      };
      pname = "uutf";
      src = pkgs.fetchurl 
      {
        sha256 = "1nx1rly3qj23jzn9yk3x6fwqimcxjd84kv5859vvhdg56psq26p6";
        url = "http://erratique.ch/software/uutf/releases/uutf-1.0.2.tbz";
      };
      version = "1.0.2";
    };
    x509 = 
    {
      opamInputs = 
      {
        asn1-combinators = selection.asn1-combinators;
        base64 = selection.base64;
        cstruct = selection.cstruct;
        domain-name = selection.domain-name;
        dune = selection.dune;
        fmt = selection.fmt;
        gmap = selection.gmap;
        logs = selection.logs;
        mirage-crypto = selection.mirage-crypto;
        mirage-crypto-pk = selection.mirage-crypto-pk;
        ocaml = selection.ocaml;
        ptime = selection.ptime;
        rresult = selection.rresult;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1cybxf9b85j2i4vpz13ffnlxv4dk5ii0ixk433i8kl1f4bg0y4gj";
        package = "packages/x509/x509.0.11.2";
      };
      pname = "x509";
      src = pkgs.fetchurl 
      {
        sha256 = "1b4lcphmlyjhdgqi0brakgjp3diwmrj1y9hx87svi5xklw3zik22";
        url = "https://github.com/mirleft/ocaml-x509/releases/download/v0.11.2/x509-v0.11.2.tbz";
      };
      version = "0.11.2";
    };
    yojson = 
    {
      opamInputs = 
      {
        biniou = selection.biniou;
        cppo = selection.cppo;
        dune = selection.dune;
        easy-format = selection.easy-format;
        ocaml = selection.ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:1vxmg1yiwh1wgxwwqzfrvaaff4wxanakq2yap1s2x3h54fqakkza";
        package = "packages/yojson/yojson.1.7.0";
      };
      pname = "yojson";
      src = pkgs.fetchurl 
      {
        sha256 = "1iich6323npvvs8r50lkr4pxxqm9mf6w67cnid7jg1j1g5gwcvv5";
        url = "https://github.com/ocaml-community/yojson/releases/download/1.7.0/yojson-1.7.0.tbz";
      };
      version = "1.7.0";
    };
    zarith = 
    {
      opamInputs = 
      {
        conf-gmp = selection.conf-gmp;
        conf-perl = selection.conf-perl;
        ocaml = selection.ocaml;
        ocamlfind = selection.ocamlfind;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        hash = "sha256:0d9qv08knlxn6p42ppc0879zi8x1z4ddl6is46ix9kgx4xgh2wic";
        package = "packages/zarith/zarith.1.11";
      };
      pname = "zarith";
      src = pkgs.fetchurl 
      {
        sha256 = "111n33flg4aq5xp5jfksqm4yyz6mzxx9ps9a4yl0dz8h189az5pr";
        url = "https://github.com/ocaml/Zarith/archive/release-1.11.tar.gz";
      };
      version = "1.11";
    };
  };
}

